polzovat_slovo = input('введите что-нибудь')
print (polzovat_slovo[1:])
print (polzovat_slovo[-1])
print (polzovat_slovo[:-2])
dlina = len(polzovat_slovo)
print (dlina)
print (polzovat_slovo.swapcase())
print ('конец задания №1')
print ('новое задание')